fullscreen = default
terminal-cursor-style = default
terminal-cursor-blink-rate = default
font-style = default
theme-style = default
shortcut-create-session = default
shortcut-next-session = default
shortcut-previous-session = default
shortcut-rename-session = default
volume-keys = default
disable-session-toast = default
transcript-rows = default
fullscreen-workaround = default
force-black-ui = default